services:
  sd.command.activate:
    class: sd\SwPluginManager\Command\ActivateCommand
  sd.command.deactivate:
    class: sd\SwPluginManager\Command\DeactivateCommand
  sd.command.install:
    class: sd\SwPluginManager\Command\InstallCommand
  sd.command.info:
    class: sd\SwPluginManager\Command\InfoCommand
  sd.command.list:
    class: sd\SwPluginManager\Command\ListCommand
  sd.command.refresh:
    class: sd\SwPluginManager\Command\RefreshCommand
  sd.command.deploy_zip:
    class: sd\SwPluginManager\Command\DeployZipCommand
  sd.command.automatic_deploy:
    class: sd\SwPluginManager\Command\AutomaticDeployCommand
    arguments:
      - '@sd.repository.statefile'
      - '@sd.worker.pluginfetcher'
      - '@sd.worker.plugindeployer'
  sd.command.fetch_plugin:
    class: sd\SwPluginManager\Command\FetchPluginCommand
    arguments:
      - '@sd.repository.statefile'
      - '@sd.worker.pluginfetcher'

  sd.factory.configuredpluginstate:
    class: sd\SwPluginManager\Factory\ConfiguredPluginStateFactory
  sd.factory.deployedpluginstate:
    class: sd\SwPluginManager\Factory\DeployedPluginStateFactory

  sd.repository.deployedplugin:
    class: sd\SwPluginManager\Repository\DeployedPluginRepository
    arguments:
      - '@sd.factory.deployedpluginstate'
  sd.repository.provider:
    class: sd\SwPluginManager\Repository\ProviderRepository
  sd.repository.statefile:
    class: sd\SwPluginManager\Repository\StateFile
    arguments:
      - '@sd.factory.configuredpluginstate'

  sd.provider.filesystem:
    class: sd\SwPluginManager\Provider\FilesystemProvider
    tags: ['sd.plugin.provider']
  sd.provider.none:
    class: sd\SwPluginManager\Provider\NoneProvider
    tags: ['sd.plugin.provider']
  sd.provider.http:
    class: sd\SwPluginManager\Provider\HttpProvider
    tags: ['sd.plugin.provider']
    arguments:
      - '@sd.external.guzzle'

  sd.worker.pluginfetcher:
    class: sd\SwPluginManager\Worker\PluginFetcher
    arguments:
      - '@sd.repository.provider'

  sd.worker.plugindeployer:
    class: sd\SwPluginManager\Worker\PluginDeployer

  sd.external.guzzle:
    class: GuzzleHttp\Client
